# Generated by Django 5.1.6 on 2026-03-28 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auteur (Détail)",
                "verbose_name_plural": "Auteurs (Détails)",
                "ordering": ["utilisateur__last_name", "utilisateur__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Bdtheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("resumé", models.TextField(verbose_name="Résumé de l'œuvre")),
                (
                    "couverture",
                    models.ImageField(
                        blank=True, null=True, upload_to="livres/couvertures/"
                    ),
                ),
                (
                    "autre_editeur_nom",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom de l'éditeur (si non listé)",
                    ),
                ),
                (
                    "valide",
                    models.BooleanField(
                        default=False, verbose_name="Est validé par l'admin"
                    ),
                ),
                (
                    "type_oeuvre",
                    models.CharField(
                        choices=[
                            ("BD", "Bande Dessinée"),
                            ("Roman", "Roman"),
                            ("Nouvelle", "Nouvelle"),
                            ("Webtoon", "Webtoon"),
                            ("Essai", "Essai"),
                            ("Manga", "Manga"),
                        ],
                        default="BD",
                        max_length=50,
                        verbose_name="Type d'œuvre",
                    ),
                ),
                (
                    "date_publication",
                    models.DateField(verbose_name="Date de publication"),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="ISBN (13 chiffres)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bdtheque",
                "verbose_name_plural": "Bdtheque",
                "ordering": ["-date_publication", "titre"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("Auteur/Dessinateur", "Auteur/Dessinateur"),
                            ("Journaliste", "Journaliste"),
                            ("Etudiant/Chercheur", "Etudiant/Chercheur"),
                            ("Grand-public", "Grand-public"),
                        ],
                        default="Journaliste",
                        max_length=50,
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=50, null=True)),
                ("prenom", models.CharField(blank=True, max_length=50, null=True)),
                ("societe", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("objet", models.CharField(blank=True, max_length=100, null=True)),
                ("message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Editeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Les Éditions Soleil Levant",
                        max_length=150,
                        unique=True,
                        verbose_name="Nom de la maison d'édition",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL unique générée (ex: les-editions-soleil-levant)",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "slogan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Slogan ou courte accroche",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Histoire et vision détaillées",
                    ),
                ),
                (
                    "adresse_siege",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Adresse du siège social",
                    ),
                ),
                (
                    "annee_fondation",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1500),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Année de fondation",
                    ),
                ),
                (
                    "email_contact",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail public de contact (si différent de l'e-mail du compte)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "site_web",
                    models.URLField(blank=True, null=True, verbose_name="Site Web"),
                ),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("siege", models.CharField(max_length=50, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="editeurs/logos/",
                        verbose_name="Logo de l'éditeur",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude du siège",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude du siège",
                    ),
                ),
                (
                    "nom_contact_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom/Prénom Contact Principal",
                    ),
                ),
                (
                    "role_contact_1",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Propriétaire", "Propriétaire"),
                            ("Employé", "Employé"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tel_contact_1",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "email_contact_1",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "nom_contact_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nom/Prénom Contact Secondaire",
                    ),
                ),
                (
                    "role_contact_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Propriétaire", "Propriétaire"),
                            ("Employé", "Employé"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tel_contact_2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "email_contact_2",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
            options={
                "verbose_name": "Éditeur (Maison Edition)",
                "verbose_name_plural": "Éditeurs (Maison Edition)",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="Jours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Librairie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "pays",
                    models.CharField(
                        choices=[
                            ("dz", "Algérie"),
                            ("ao", "Angola"),
                            ("bj", "Bénin"),
                            ("bw", "Botswana"),
                            ("bf", "Burkina Faso"),
                            ("bi", "Burundi"),
                            ("cm", "Cameroun"),
                            ("cv", "Cap-Vert"),
                            ("cf", "République Centrafricaine"),
                            ("td", "Tchad"),
                            ("km", "Comores"),
                            ("cg", "Congo-Brazzaville"),
                            ("cd", "Congo-Kinshasa"),
                            ("dj", "Djibouti"),
                            ("eg", "Égypte"),
                            ("gq", "Guinée Équatoriale"),
                            ("er", "Érythrée"),
                            ("sz", "Eswatini"),
                            ("et", "Éthiopie"),
                            ("ga", "Gabon"),
                            ("gm", "Gambie"),
                            ("gh", "Ghana"),
                            ("gn", "Guinée"),
                            ("gw", "Guinée-Bissau"),
                            ("ci", "Côte d'Ivoire"),
                            ("ke", "Kenya"),
                            ("ls", "Lesotho"),
                            ("lr", "Libéria"),
                            ("ly", "Libye"),
                            ("mg", "Madagascar"),
                            ("mw", "Malawi"),
                            ("ml", "Mali"),
                            ("mr", "Mauritanie"),
                            ("mu", "Maurice"),
                            ("ma", "Maroc"),
                            ("mz", "Mozambique"),
                            ("na", "Namibie"),
                            ("ne", "Niger"),
                            ("ng", "Nigéria"),
                            ("rw", "Rwanda"),
                            ("st", "Sao Tomé-et-Principe"),
                            ("sn", "Sénégal"),
                            ("sc", "Seychelles"),
                            ("sl", "Sierra Leone"),
                            ("so", "Somalie"),
                            ("za", "Afrique du Sud"),
                            ("ss", "Soudan du Sud"),
                            ("sd", "Soudan"),
                            ("tz", "Tanzanie"),
                            ("tg", "Togo"),
                            ("tn", "Tunisie"),
                            ("ug", "Ouganda"),
                            ("zm", "Zambie"),
                            ("zw", "Zimbabwe"),
                        ],
                        max_length=100,
                    ),
                ),
                ("ville", models.CharField(max_length=150)),
                ("enseigne", models.CharField(blank=True, max_length=255, null=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="media/")),
                ("a_propos", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=50, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("map_url", models.URLField(blank=True, null=True)),
                ("heures_ouverture", models.TimeField(blank=True, null=True)),
                ("heure_fermeture", models.TimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                ("site_web", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("tiktok", models.URLField(blank=True, null=True)),
                ("vedette", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Notation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "other_editor_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Maison d'édition s'il n'existe pas(listé)",
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        choices=[
                            ("Numerique", "Numerique"),
                            ("Physique", "Physique"),
                            ("Physique_&_Numerique", "Physique_&_Numerique"),
                        ],
                        default="Physique",
                        max_length=50,
                    ),
                ),
                (
                    "influence",
                    models.CharField(
                        choices=[
                            ("Franco-Belge", "Franco-Belge"),
                            ("Comic-US", "Comic-US"),
                            ("manga", "manga"),
                            ("webton", "webton"),
                            ("fusion", "fusion"),
                            ("alternative", "alternative"),
                        ],
                        default="Comic-US",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                ("description", models.TextField()),
                (
                    "genres",
                    models.CharField(
                        choices=[
                            ("Comedie", "Comedie"),
                            ("Aventure", "Aventure"),
                            ("Fantastique", "Fantastique"),
                            ("Histoire", "Histoire"),
                            ("Humour", "Humour"),
                            ("Science-fiction", "Science-fiction"),
                            ("Jeunesse", "Jeunesse"),
                            ("Suspense", "Suspense"),
                            ("Western", "Western"),
                            ("Romance", "Romance"),
                            ("Polar", "Polar"),
                            ("Tranche_de_vie", "Tranche_de_vie"),
                        ],
                        default="Comedie",
                        max_length=50,
                    ),
                ),
                (
                    "planche1",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                (
                    "planche2",
                    models.ImageField(blank=True, null=True, upload_to="media/"),
                ),
                ("valid", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Actualités",
            },
        ),
    ]
