# Generated by Django 5.1.6 on 2025-02-10 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_content', '0001_initial'),
        ('gestion_utilisateur', '0002_auteur_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='gestion_utilisateur.auteur'),
        ),
        migrations.AddField(
            model_name='work',
            name='genres',
            field=models.ManyToManyField(related_name='works', to='gestion_content.genre'),
        ),
        migrations.AddField(
            model_name='notation',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notation', to='gestion_content.work'),
        ),
    ]
