# Generated by Django 5.1.6 on 2026-03-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion_content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auteur",
            name="utilisateur",
            field=models.OneToOneField(
                limit_choices_to={"role": "auteur"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details_auteur",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte Utilisateur de l'Auteur",
            ),
        ),
        migrations.AddField(
            model_name="bdtheque",
            name="auteur_principal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livres_principaux",
                to="gestion_content.auteur",
            ),
        ),
        migrations.AddField(
            model_name="bdtheque",
            name="auteurs_secondaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="livres_secondaires",
                to="gestion_content.auteur",
                verbose_name="Auteurs Additionnels",
            ),
        ),
        migrations.AddField(
            model_name="editeur",
            name="utilisateur",
            field=models.ForeignKey(
                limit_choices_to={"role": "editeur"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details_editeur",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte Utilisateur de l'Éditeur",
            ),
        ),
        migrations.AddField(
            model_name="bdtheque",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livres_publies",
                to="gestion_content.editeur",
                verbose_name="Maison d'Édition enregistrée",
            ),
        ),
        migrations.AddField(
            model_name="bdtheque",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="livres_associes", to="gestion_content.genre"
            ),
        ),
        migrations.AddField(
            model_name="librairie",
            name="jours_ouverture",
            field=models.ManyToManyField(blank=True, to="gestion_content.jours"),
        ),
        migrations.AddField(
            model_name="notation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="editeur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works_submitted",
                to="gestion_content.editeur",
                verbose_name="Maison d'édition",
            ),
        ),
        migrations.AddField(
            model_name="notation",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notation",
                to="gestion_content.work",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bdtheque",
            unique_together={("edition", "titre")},
        ),
    ]
