# Generated by Django 5.1.6 on 2026-03-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_content", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="work",
            options={"verbose_name_plural": "Oeuvres"},
        ),
    ]
