# Generated by Django 5.1.6 on 2025-11-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
