# Generated by Django 5.1.6 on 2026-05-04 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'is_auteur': True}, on_delete=django.db.models.deletion.CASCADE, related_name='details_auteur', to=settings.AUTH_USER_MODEL, verbose_name="Compte Utilisateur de l'Auteur"),
        ),
        migrations.AlterField(
            model_name='editeur',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'is_editeur': True}, on_delete=django.db.models.deletion.CASCADE, related_name='details_editeur', to=settings.AUTH_USER_MODEL, verbose_name="Compte Utilisateur de l'Éditeur"),
        ),
    ]
