# Generated by Django 5.1.6 on 2026-05-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0003_alter_auteur_utilisateur_alter_editeur_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='BdthequeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='livres/couvertures/')),
                ('bd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion_content.bdtheque')),
            ],
            options={
                'verbose_name': 'Image de couverture supplémentaire',
                'verbose_name_plural': 'Images de couverture supplémentaires',
            },
        ),
    ]
