# Generated by Django 5.1.6 on 2026-04-27 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_duplicate_editeurs(apps, schema_editor):
    Editeur = apps.get_model('gestion_content', 'Editeur')
    # Group by utilisateur and keep only the first one
    seen = set()
    duplicates = []
    for editeur in Editeur.objects.all().order_by('id'):
        if editeur.utilisateur_id in seen:
            duplicates.append(editeur.id)
        else:
            seen.add(editeur.utilisateur_id)
    Editeur.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0003_alter_work_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_editeurs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='editeur',
            name='utilisateur',
            field=models.OneToOneField(limit_choices_to={'role': 'editeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='details_editeur', to=settings.AUTH_USER_MODEL, verbose_name="Compte Utilisateur de l'Éditeur"),
        ),
    ]
