# Generated by Django 5.1.6 on 2025-03-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0003_alter_work_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='genres',
        ),
        migrations.AlterField(
            model_name='work',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='work',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_content.genre'),
        ),
    ]
