# Generated by Django 5.1.6 on 2025-11-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0003_work_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='edition',
            field=models.CharField(choices=[('Numerique', 'Numerique'), ('Physique', 'Physique'), ('Physique_&_Numerique', 'Physique_&_Numerique')], default='Physique', max_length=50),
        ),
        migrations.AlterField(
            model_name='work',
            name='genres',
            field=models.CharField(choices=[('Comedie', 'Comedie'), ('Aventure', 'Aventure'), ('Fantastique', 'Fantastique'), ('Histoire', 'Histoire'), ('Humour', 'Humour'), ('Science-fiction', 'Science-fiction'), ('Jeunesse', 'Jeunesse'), ('Suspense', 'Suspense'), ('Western', 'Western'), ('Romance', 'Romance'), ('Polar', 'Polar'), ('Tranche_de_vie', 'Tranche_de_vie')], default='Comedie', max_length=50),
        ),
    ]
