# Generated by Django 5.1.6 on 2026-05-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0004_work_image2_work_image3_bdthequeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion_content.work')),
            ],
            options={
                'verbose_name': 'Image de couverture supplémentaire (Œuvre)',
                'verbose_name_plural': 'Images de couverture supplémentaires (Œuvre)',
            },
        ),
    ]
