# Generated by Django 5.1.6 on 2025-03-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0004_remove_work_genres_alter_work_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='gestion_content.genre'),
        ),
    ]
