# Generated by Django 5.1.6 on 2025-05-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0004_alter_work_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
