# Generated by Django 5.1.6 on 2025-11-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0004_work_edition_alter_work_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='influence',
            field=models.CharField(choices=[('Franco-Belge', 'Franco-Belge'), ('Comic-US', 'Comic-US'), ('manga', 'manga'), ('webton', 'webton'), ('fusion', 'fusion'), ('alternative', 'alternative')], default='Comic-US', max_length=50),
        ),
        migrations.AddField(
            model_name='work',
            name='planche1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='work',
            name='planche2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
