# Generated by Django 5.1.6 on 2025-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0005_work_influence_work_planche1_work_planche2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Librairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pays', models.CharField(choices=[('dz', 'Algérie'), ('ao', 'Angola'), ('bj', 'Bénin'), ('bw', 'Botswana'), ('bf', 'Burkina Faso'), ('bi', 'Burundi'), ('cm', 'Cameroun'), ('cv', 'Cap-Vert'), ('cf', 'République Centrafricaine'), ('td', 'Tchad'), ('km', 'Comores'), ('cg', 'Congo-Brazzaville'), ('cd', 'Congo-Kinshasa'), ('dj', 'Djibouti'), ('eg', 'Égypte'), ('gq', 'Guinée Équatoriale'), ('er', 'Érythrée'), ('sz', 'Eswatini'), ('et', 'Éthiopie'), ('ga', 'Gabon'), ('gm', 'Gambie'), ('gh', 'Ghana'), ('gn', 'Guinée'), ('gw', 'Guinée-Bissau'), ('ci', "Côte d'Ivoire"), ('ke', 'Kenya'), ('ls', 'Lesotho'), ('lr', 'Libéria'), ('ly', 'Libye'), ('mg', 'Madagascar'), ('mw', 'Malawi'), ('ml', 'Mali'), ('mr', 'Mauritanie'), ('mu', 'Maurice'), ('ma', 'Maroc'), ('mz', 'Mozambique'), ('na', 'Namibie'), ('ne', 'Niger'), ('ng', 'Nigéria'), ('rw', 'Rwanda'), ('st', 'Sao Tomé-et-Principe'), ('sn', 'Sénégal'), ('sc', 'Seychelles'), ('sl', 'Sierra Leone'), ('so', 'Somalie'), ('za', 'Afrique du Sud'), ('ss', 'Soudan du Sud'), ('sd', 'Soudan'), ('tz', 'Tanzanie'), ('tg', 'Togo'), ('tn', 'Tunisie'), ('ug', 'Ouganda'), ('zm', 'Zambie'), ('zw', 'Zimbabwe')], max_length=100)),
                ('ville', models.CharField(max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='librairies/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='librairies/')),
                ('vedette', models.BooleanField(default=False)),
                ('valide', models.BooleanField(default=False)),
            ],
        ),
    ]
