# Generated by Django 5.1.6 on 2026-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0005_workimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='planche1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='planche2',
        ),
        migrations.AddField(
            model_name='work',
            name='toms1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Tome 1'),
        ),
        migrations.AddField(
            model_name='work',
            name='toms2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Tome 2'),
        ),
        migrations.AddField(
            model_name='work',
            name='toms3',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Tome 3'),
        ),
        migrations.AddField(
            model_name='work',
            name='toms4',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Tome 4'),
        ),
        migrations.AddField(
            model_name='work',
            name='toms5',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Tome 5'),
        ),
    ]
