# Generated by Django 5.1.6 on 2026-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0006_remove_work_planche1_remove_work_planche2_work_toms1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='planche1',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Planche 1'),
        ),
        migrations.AddField(
            model_name='work',
            name='planche2',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Planche 2'),
        ),
    ]
