# Generated by Django 5.1.6 on 2025-11-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0006_librairie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librairie',
            old_name='image1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='librairie',
            name='image2',
        ),
        migrations.AddField(
            model_name='librairie',
            name='a_propos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='enseigne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='heure_fermeture',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='heures_ouverture',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='librairie',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librairie',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='librairie',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
