# Generated by Django 5.1.6 on 2026-05-27 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0007_work_planche1_work_planche2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='media/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomes', to='gestion_content.work')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('work', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Planche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('tome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planches', to='gestion_content.tome')),
            ],
            options={
                'verbose_name': 'Planche',
                'verbose_name_plural': 'Planches',
            },
        ),
    ]
