# Generated by Django 5.1.6 on 2026-05-28 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0008_tome_planche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='planche1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='planche2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='toms1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='toms2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='toms3',
        ),
        migrations.RemoveField(
            model_name='work',
            name='toms4',
        ),
        migrations.RemoveField(
            model_name='work',
            name='toms5',
        ),
    ]
