# Generated by Django 5.1.6 on 2025-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0008_librairie_latitude_librairie_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('Auteur/Dessinateur', 'Auteur/Dessinateur'), ('Journaliste', 'Journaliste'), ('Etudiant/Chercheur', 'Etudiant/Chercheur'), ('Grand-public', 'Grand-public')], default='Journaliste', max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('societe', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
