# Generated by Django 5.1.6 on 2026-05-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0009_remove_work_planche1_remove_work_planche2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image3',
        ),
    ]
