# Generated by Django 5.1.6 on 2025-11-11 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0009_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Les Éditions Soleil Levant', max_length=150, unique=True, verbose_name="Nom de la maison d'édition")),
                ('slug', models.SlugField(blank=True, help_text='URL unique générée (ex: les-editions-soleil-levant)', max_length=150, unique=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Slogan ou courte accroche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Histoire et vision détaillées')),
                ('adresse_siege', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du siège social')),
                ('annee_fondation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2100)], verbose_name='Année de fondation')),
                ('email_contact', models.EmailField(blank=True, help_text="E-mail public de contact (si différent de l'e-mail du compte)", max_length=100, null=True)),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='editeurs/logos/', verbose_name="Logo de l'éditeur")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude du siège')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude du siège')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'editeur'}, on_delete=django.db.models.deletion.CASCADE, related_name='details_editeur', to=settings.AUTH_USER_MODEL, verbose_name="Compte Utilisateur de l'Éditeur")),
            ],
            options={
                'verbose_name': 'Éditeur (Détail)',
                'verbose_name_plural': 'Éditeurs (Détails)',
                'ordering': ['nom'],
            },
        ),
    ]
