# Generated by Django 5.1.6 on 2025-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0010_editeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='editeur',
            name='siege',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
