# Generated by Django 5.1.6 on 2025-11-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0011_editeur_siege'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='nom',
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'auteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='details_auteur', to=settings.AUTH_USER_MODEL, verbose_name="Compte Utilisateur de l'Auteur")),
            ],
            options={
                'verbose_name': 'Auteur (Détail)',
                'verbose_name_plural': 'Auteurs (Détails)',
                'ordering': ['utilisateur__last_name', 'utilisateur__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('resumé', models.TextField(verbose_name="Résumé de l'œuvre")),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='livres/couvertures/')),
                ('type_oeuvre', models.CharField(choices=[('BD', 'Bande Dessinée'), ('Roman', 'Roman'), ('Nouvelle', 'Nouvelle'), ('Webtoon', 'Webtoon'), ('Essai', 'Essai'), ('Manga', 'Manga')], default='BD', max_length=50, verbose_name="Type d'œuvre")),
                ('date_publication', models.DateField(verbose_name='Date de publication')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN (13 chiffres)')),
                ('auteur_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres_principaux', to='gestion_content.auteur')),
                ('auteurs_secondaires', models.ManyToManyField(blank=True, related_name='livres_secondaires', to='gestion_content.auteur', verbose_name='Auteurs Additionnels')),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres_publies', to='gestion_content.editeur')),
                ('genres', models.ManyToManyField(blank=True, related_name='livres_associes', to='gestion_content.genre')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-date_publication', 'titre'],
                'unique_together': {('editeur', 'titre')},
            },
        ),
    ]
