# Generated by Django 5.1.6 on 2025-11-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_content",
            "0012_alter_genre_options_rename_name_genre_nom_genre_slug_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Livre",
            new_name="Bdtheque",
        ),
        migrations.AlterField(
            model_name="librairie",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
