# Generated by Django 5.1.6 on 2025-11-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_content", "0013_rename_livre_bdtheque_alter_librairie_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bdtheque",
            options={
                "ordering": ["-date_publication", "titre"],
                "verbose_name": "Bdtheque",
                "verbose_name_plural": "Bdtheque",
            },
        ),
    ]
