# Generated by Django 5.1.6 on 2025-11-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_content", "0014_alter_bdtheque_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bdtheque",
            old_name="editeur",
            new_name="edition",
        ),
        migrations.AlterUniqueTogether(
            name="bdtheque",
            unique_together={("edition", "titre")},
        ),
    ]
