# Generated by Django 5.1.6 on 2026-01-30 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_content", "0015_rename_editeur_bdtheque_edition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bdtheque",
            name="autre_editeur_nom",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nom de l'éditeur (si non listé)",
            ),
        ),
        migrations.AddField(
            model_name="bdtheque",
            name="valide",
            field=models.BooleanField(
                default=False, verbose_name="Est validé par l'admin"
            ),
        ),
        migrations.AddField(
            model_name="editeur",
            name="email_contact_1",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="editeur",
            name="email_contact_2",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="editeur",
            name="nom_contact_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nom/Prénom Contact Principal",
            ),
        ),
        migrations.AddField(
            model_name="editeur",
            name="nom_contact_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nom/Prénom Contact Secondaire",
            ),
        ),
        migrations.AddField(
            model_name="editeur",
            name="role_contact_1",
            field=models.CharField(
                blank=True,
                choices=[("Propriétaire", "Propriétaire"), ("Employé", "Employé")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="editeur",
            name="role_contact_2",
            field=models.CharField(
                blank=True,
                choices=[("Propriétaire", "Propriétaire"), ("Employé", "Employé")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="editeur",
            name="tel_contact_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="editeur",
            name="tel_contact_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bdtheque",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livres_publies",
                to="gestion_content.editeur",
                verbose_name="Maison d'Édition enregistrée",
            ),
        ),
    ]
