# Generated by Django 5.1.6 on 2025-11-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_link',
            name='platform',
        ),
        migrations.AddField(
            model_name='social_link',
            name='plateforme',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('Site-web', 'Site-web')], max_length=120, null=True),
        ),
    ]
