# Generated by Django 5.1.6 on 2026-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_auteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_autre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_editeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_libraire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_organisateur',
            field=models.BooleanField(default=False, verbose_name="Organisateur d'Évènement"),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('lecteur', 'Lecteur'), ('auteur', 'Auteur/Dessinateur'), ('editeur', "Maison d'Édition")], default='lecteur', max_length=50),
        ),
    ]
