# Generated by Django 5.1.6 on 2025-05-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='evenement',
            name='date_publication',
            field=models.DateField(auto_now=True),
        ),
    ]
