# Generated by Django 5.1.6 on 2025-05-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0002_remove_evenement_date_fin_evenement_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='heure_evenement',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
