# Generated by Django 5.1.6 on 2025-11-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestion_utilisateur",
            "0002_remove_social_link_platform_social_link_plateforme",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="utilisateur",
            old_name="valid_auteur",
            new_name="valid",
        ),
    ]
