# Generated by Django 5.1.6 on 2026-05-04 05:24

from django.db import migrations


def migrate_roles(apps, schema_editor):
    Utilisateur = apps.get_model('gestion_utilisateur', 'Utilisateur')
    for user in Utilisateur.objects.all():
        if user.role == 'auteur':
            user.is_auteur = True
        elif user.role == 'editeur':
            user.is_editeur = True
        # Ajoutez des conditions si d'autres rôles existent, ex: 'libraire', 'organisateur'
        user.save()

def reverse_migrate_roles(apps, schema_editor):
    Utilisateur = apps.get_model('gestion_utilisateur', 'Utilisateur')
    for user in Utilisateur.objects.all():
        if user.is_auteur:
            user.role = 'auteur'
        elif user.is_editeur:
            user.role = 'editeur'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0002_add_boolean_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
