# Generated by Django 5.1.6 on 2025-11-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_utilisateur", "0003_rename_valid_auteur_utilisateur_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="token",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
