# Generated by Django 5.1.6 on 2025-02-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0003_remove_utilisateur_social_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
