# Generated by Django 5.1.6 on 2026-05-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0003_migrate_roles_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
    ]
