# Generated by Django 5.1.6 on 2025-05-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0004_participationevenement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipationEvenement',
        ),
    ]
