# Generated by Django 5.1.6 on 2025-03-02 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0002_initial'),
        ('gestion_utilisateur', '0004_alter_auteur_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='annee_experience',
            field=models.CharField(blank=True, choices=[('0-2 ans', '0-2 ans'), ('3-5 ans', '3-5 ans'), ('5-10 ans', '5-10 ans'), ('plus de 10 ans', 'plus de 10 ans')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='gestion_content.genre'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
