# Generated by Django 5.1.6 on 2026-05-04 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0004_remove_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='organisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Organisateur'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='valide',
            field=models.BooleanField(default=False, verbose_name="Approuvé par l'admin"),
        ),
    ]
