# Generated by Django 5.1.6 on 2025-05-07 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0005_delete_participationevenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_fin_evenement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='lieu_evenement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ParticipationEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('date_participation', models.DateTimeField(blank=True, null=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_utilisateur.evenement')),
            ],
        ),
    ]
