# Generated by Django 5.1.6 on 2026-05-04 05:33

from django.db import migrations


def make_events_valid(apps, schema_editor):
    Evenement = apps.get_model('gestion_utilisateur', 'Evenement')
    Evenement.objects.all().update(valide=True)

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0005_add_evenement_validation'),
    ]

    operations = [
        migrations.RunPython(make_events_valid, reverse_code=migrations.RunPython.noop),
    ]
