# Generated by Django 5.1.6 on 2025-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_utilisateur", "0005_remove_utilisateur_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="couleur_evenement",
            field=models.CharField(
                default="#007bff", max_length=7, verbose_name="Couleur de l'événement"
            ),
        ),
    ]
