# Generated by Django 5.1.6 on 2025-11-22 06:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_utilisateur", "0006_evenement_couleur_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="couleur_evenement",
            field=colorfield.fields.ColorField(
                default="#007bff",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Couleur de l'événement",
            ),
        ),
    ]
