# Generated by Django 5.1.6 on 2025-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0006_utilisateur_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='genres',
        ),
    ]
