# Generated by Django 5.1.6 on 2026-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0006_set_existing_events_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_illustrateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_scenariste',
            field=models.BooleanField(default=False),
        ),
    ]
