# Generated by Django 5.1.6 on 2025-05-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0006_evenement_date_fin_evenement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='annee_experience',
        ),
    ]
