# Generated by Django 5.1.6 on 2026-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_utilisateur", "0007_alter_evenement_couleur_evenement"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="change_pwd",
            field=models.BooleanField(default=True),
        ),
    ]
