# Generated by Django 5.1.6 on 2025-03-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0007_remove_utilisateur_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('auteur', 'auteur'), ('lecteur', 'lecteur')], default='lecteur', max_length=120),
        ),
    ]
