# Generated by Django 5.1.6 on 2025-05-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0007_remove_utilisateur_annee_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='vedette',
            field=models.BooleanField(default=False),
        ),
    ]
