# Generated by Django 5.1.6 on 2026-02-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_utilisateur", "0008_utilisateur_change_pwd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilisateur",
            name="change_pwd",
        ),
    ]
