# Generated by Django 5.1.6 on 2025-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0009_alter_utilisateur_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
