# Generated by Django 5.1.6 on 2025-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0010_utilisateur_date_naissance_utilisateur_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url_actu',
            field=models.URLField(blank=True, null=True),
        ),
    ]
