# Generated by Django 5.1.6 on 2025-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0010_alter_blogpost_author_delete_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='updated_at',
            new_name='media',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
