# Generated by Django 5.1.6 on 2025-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0011_rename_updated_at_blogpost_media_blogpost_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
