# Generated by Django 5.1.6 on 2025-05-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0011_blogpost_url_actu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('auteur', 'auteur'), ('editeur', 'editeur'), ('libraire', 'libraire'), ('organisateur_Evènement', 'organisateur_Evènement'), ('autre', 'autre')], default='auteur', max_length=120),
        ),
    ]
