# Generated by Django 5.1.6 on 2025-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0013_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
