# Generated by Django 5.1.6 on 2025-03-14 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0014_evenement_date_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='pays',
            new_name='nationalite',
        ),
    ]
