# Generated by Django 5.1.6 on 2025-03-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0015_rename_pays_utilisateur_nationalite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nationalite',
            new_name='pays',
        ),
    ]
