# Generated by Django 5.1.6 on 2025-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0017_alter_utilisateur_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(choices=[('DZ', 'Algérie'), ('AO', 'Angola'), ('BJ', 'Bénin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroun'), ('CV', 'Cap-Vert'), ('CF', 'République Centrafricaine'), ('TD', 'Tchad'), ('KM', 'Comores'), ('CG', 'Congo-Brazzaville'), ('CD', 'Congo-Kinshasa'), ('DJ', 'Djibouti'), ('EG', 'Égypte'), ('GQ', 'Guinée Équatoriale'), ('ER', 'Érythrée'), ('SZ', 'Eswatini'), ('ET', 'Éthiopie'), ('GA', 'Gabon'), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('GW', 'Guinée-Bissau'), ('CI', "Côte d'Ivoire"), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Libéria'), ('LY', 'Libye'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('MU', 'Maurice'), ('MA', 'Maroc'), ('MZ', 'Mozambique'), ('NA', 'Namibie'), ('NE', 'Niger'), ('NG', 'Nigéria'), ('RW', 'Rwanda'), ('ST', 'Sao Tomé-et-Principe'), ('SN', 'Sénégal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalie'), ('ZA', 'Afrique du Sud'), ('SS', 'Soudan du Sud'), ('SD', 'Soudan'), ('TZ', 'Tanzanie'), ('TG', 'Togo'), ('TN', 'Tunisie'), ('UG', 'Ouganda'), ('ZM', 'Zambie'), ('ZW', 'Zimbabwe')], default='CM', max_length=100, null=True),
        ),
    ]
