# Generated by Django 5.1.6 on 2025-03-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0018_alter_utilisateur_pays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='valid',
            new_name='valid_auteur',
        ),
    ]
