# Generated by Django 5.1.6 on 2025-03-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0019_rename_valid_utilisateur_valid_auteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='password_confirme',
        ),
    ]
