# Generated by Django 5.1.6 on 2025-03-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_content', '0003_alter_work_author'),
        ('gestion_utilisateur', '0020_remove_utilisateur_password_confirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='auteurs', to='gestion_content.genre'),
        ),
    ]
