# Generated by Django 5.1.6 on 2025-03-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0021_utilisateur_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='profil_picture',
        ),
    ]
