# Generated by Django 5.1.6 on 2025-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0022_remove_utilisateur_profil_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
