# Generated by Django 5.1.6 on 2025-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateur', '0023_utilisateur_profil_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='pays',
            field=models.CharField(choices=[('Algérie', 'Algérie'), ('Angola', 'Angola'), ('Bénin', 'Bénin'), ('Botswana', 'Botswana'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cameroun', 'Cameroun'), ('Cap-Vert', 'Cap-Vert'), ('République Centrafricaine', 'République Centrafricaine'), ('Tchad', 'Tchad'), ('Comores', 'Comores'), ('Congo-Brazzaville', 'Congo-Brazzaville'), ('Congo-Kinshasa', 'Congo-Kinshasa'), ('Djibouti', 'Djibouti'), ('Égypte', 'Égypte'), ('Guinée Équatoriale', 'Guinée Équatoriale'), ('Érythrée', 'Érythrée'), ('Eswatini', 'Eswatini'), ('Éthiopie', 'Éthiopie'), ('Gabon', 'Gabon'), ('Gambie', 'Gambie'), ('Ghana', 'Ghana'), ('Guinée', 'Guinée'), ('Guinée-Bissau', 'Guinée-Bissau'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Kenya', 'Kenya'), ('Lesotho', 'Lesotho'), ('Libéria', 'Libéria'), ('Libye', 'Libye'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Mali', 'Mali'), ('Mauritanie', 'Mauritanie'), ('Maurice', 'Maurice'), ('Maroc', 'Maroc'), ('Mozambique', 'Mozambique'), ('Namibie', 'Namibie'), ('Niger', 'Niger'), ('Nigéria', 'Nigéria'), ('Rwanda', 'Rwanda'), ('Sao Tomé-et-Principe', 'Sao Tomé-et-Principe'), ('Sénégal', 'Sénégal'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Somalie', 'Somalie'), ('Afrique du Sud', 'Afrique du Sud'), ('Soudan du Sud', 'Soudan du Sud'), ('Soudan', 'Soudan'), ('Tanzanie', 'Tanzanie'), ('Togo', 'Togo'), ('Tunisie', 'Tunisie'), ('Ouganda', 'Ouganda'), ('Zambie', 'Zambie'), ('Zimbabwe', 'Zimbabwe')], default='CM', max_length=100, null=True),
        ),
    ]
